# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9bec765e7ac54340f1a9d1a79fb17f0bc293f73fa62b024f72768d0825e1e7bd3bfe4ef65f992c3d0538c8c3fb0725b159c604ed38ca572a4aa16d5611a8013

test:
  secret_key_base: 6842ad36e48796c0116fa3ef3357860111800aa0a03b78fb2ccf124c4769f832935babc4f539a5d97c09c28ab94ed10d2af2b820f5b818022baa5e901deb7495

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
